name: Publish to npm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      - name: prepublishOnly
        run: npm prepublishOnly

      - name: Compressing artifacts 🗜
        run: zip -r -q artifacts.zip .
        
      - name: Saving workflow artifacts 📦
        uses: actions/upload-artifact@v3
        with:
          name: application-build
          retention-days: 1
          path: artifacts.zip

      # Add your build or test scripts here
      # - name: Run tests
      #   run: npm test

      #- name: Publish to npm
      #  run: npm publish
       # env:
       #   NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
